name: build & deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      N2YO_API_KEY: ${{ secrets.N2YO_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps for C (curl)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libcurl4-openssl-dev

      - name: Build C fetcher
        run: |
          make -C c clean || true
          make -C c

      - name: Run fetcher to update data.json
        run: |
          ./c/satellite ./c/sats.txt
          mkdir -p public
          cp c/data.json public/data.json

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install deps & build site
        run: |
          npm ci
          npm run build

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
